### ISSUE TITLE
single newlines \n not working in message text

### ISSUE THREAD

**Issue by aplsysmngr** [bartreardon/Dialog#57]
Thanks for a promising tool!

Single newlines \n are not working in message text, \n is rendered as a space, not as new line.
Double newlines \n\n are working ok and leave an empty line between text rows.

Non-working example:
dialog --title "Please read this message" --message "Line 1\nLine 2\nLine 3" 

MacOS 11.6, Intel, dialog v.1.8.0

**Comment by bartreardon** [comment]
Hey thanks for checking out dialog.

The double newline is a quirk of markdown which is what's being used to render the message area. Commonmark follows the [original spec](https://daringfireball.net/projects/markdown/syntax#p) in this regard particularly:

> When you do want to insert a `<br />` break tag using Markdown, you end a line with two or more spaces, then type return.

A double newline such as `Line 1\n\nLine 2` will put `Line 2` on a new paragraph. 
<img width="727" alt="image" src="https://user-images.githubusercontent.com/3598965/139531609-34df0f08-811c-4ddd-bb8c-18e3e3cf1d71.png">


If you use two space characters at the end of the line like so `Line 1  \nLine 2` then `Line 2` will immediately precede Line 1
<img width="727" alt="image" src="https://user-images.githubusercontent.com/3598965/139531621-25060b0f-f3aa-4c1d-995e-c3a7c04042b2.png">


It raises an interesting point however as "fixing" this so a single `\n` may break existing implementations. I can address this behaviour in the wiki and help text though to make it clearer.

In older versions of dialog that didn't use markdown, a single `\n` would indeed break a line.

**Comment by aplsysmngr** [comment]
OK, I got it sorted out. Thanks for the clarification, this would be good to include in the wiki.

**Comment by bartreardon** [comment]
Yup. Wiki has been updated here. 

https://github.com/bartreardon/Dialog-public/wiki/Customising-the-Message-area#newlines
