### ISSUE TITLE
infobutton not working in 1.8.1?

### ISSUE THREAD

**Issue by aplsysmngr** [bartreardon/Dialog#61]
Seems that infobutton is not working in 1.8.1:

```shell
dialog --button1text "Open MSC" --button2text "Cancel" --infobuttontext "More Info"
#echo $?
case $? in
  0)
  	echo "Opening MSC"
  	open -a "/Applications/Managed Software Center.app"
  	;;
  2)
  	echo "Pressed Cancel"
  	;;
  3)
  	echo "More Info requested"
  	;;
  *)
  	echo "Something else happened"
  	;;
esac
```

**Comment by bartreardon** [comment]
the behaviour changed in 1.8.0 so by default the info button performs `--infobuttonaction` but does not exit  https://github.com/bartreardon/Dialog/wiki/Buttons-and-button-behaviour#the-more-information-button

if you want the infobutton to exit dialog with exit code 3, add `--quitoninfo` to your command.

**Comment by aplsysmngr** [comment]
OK, I got it working on 1.8.1 as you suggested...false alarm.

**Comment by bartreardon** [comment]
No problemo 👍🙂
