### ISSUE TITLE
--timer and --button1text used together cause an application hang

### ISSUE THREAD

**Issue by kdrwygvh** [bartreardon/Dialog#73]
When specifying a --timer value of any length along with a --button1text value, the 3 second delay until button1 activation never occurs nor does the --timer ever begin to deincrement. Application seems to be hung at this point. Removing either --timer or --button1text resolves the issue.

**Comment by bartreardon** [comment]
thanks - I can confirm this behaviour. Seems to get itself into a loop before initiating the timer

**Comment by bartreardon** [comment]
@kdrwygvh this build should work for you. LMK if there's any issues
[dialog-1.9.2-Preview1.pkg.zip](https://github.com/bartreardon/Dialog/files/8078409/dialog-1.9.2-Preview1.pkg.zip)

**Comment by bartreardon** [comment]
fixed in the latest release
