### ISSUE TITLE
Videos not working in 1.9.2

### ISSUE THREAD

**Issue by TheFritz01** [bartreardon/Dialog#80]
When attempting to run a dialog that contains an MP4 in 1.9.2, I get the following error

` /usr/local/bin/dialog --title "Test Title" --video "/Users/Shared/Sample.mp4" --videocaption "Test Caption"`
`failed to demangle superclass of VideoPlayerView from mangled name 'So12AVPlayerViewC': unknown error`

However, in version 1.8.1 the same command works perfectly.

**Comment by bartreardon** [comment]
Interesting bug. the video code hasn't been modified between 1.8 and 1.9 but I have an idea.

**Comment by bartreardon** [comment]
fixed in [1.9.3](https://github.com/bartreardon/Dialog/releases/tag/v1.9.3)

**Comment by TheFritz01** [comment]
Thanks, I verified on my end that videos are now working.  The only thing I noticed is that for  --image dialogs, the content is scaled a bit smaller than with 1.8.1.   Not a big deal. Just thought I would pass it along. 
 
![Screen Shot 2022-03-04 at 9 01 48 AM](https://user-images.githubusercontent.com/8322797/156787012-fef93617-a670-4d96-959b-1fb2428c5017.png)

**Comment by bartreardon** [comment]
ah - ok - yeah, that's to do with the image carousel that was introduced in 1.9.

I've had a look at the code and have fixed up the rendering when there is only a single image present. Will be updated in the next release.
